from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "creative_blueprint.json"


def state(
    state_id: str,
    location: str,
    lighting: str,
    visible_characters: list[str],
    props: list[str],
    screen_direction: str,
    audio_state: str,
) -> dict[str, Any]:
    return {
        "id": state_id,
        "location": location,
        "lighting": lighting,
        "visible_characters": visible_characters,
        "props": props,
        "screen_direction": screen_direction,
        "audio_state": audio_state,
    }


def build_states() -> dict[str, dict[str, Any]]:
    return {
        "study_open": state(
            "study_open",
            "苏宅书斋",
            "日间窗格侧光与低暖烛光",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.closed", "oil_lamp.one.steady"],
            "程夫人在案后；苏轼右侧、苏辙左侧；巢儿在右后门角",
            "书斋低室内声，竹叶远响，尚未开始对白",
        ),
        "study_reciting_start": state(
            "study_reciting_start",
            "苏宅书斋",
            "日间窗格侧光与低暖烛光",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "四人站位不变，视线朝向案后与书卷",
            "程夫人开始低声诵读，三名少年屏息听讲",
        ),
        "study_listening": state(
            "study_listening",
            "苏宅书斋",
            "柔和纸灰与木棕色调",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "苏轼、苏辙面向案后；巢儿在右后向前探听",
            "诵读连续，布料和轻微呼吸可闻",
        ),
        "study_page_ready": state(
            "study_page_ready",
            "苏宅书斋",
            "柔和纸灰与木棕色调",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "程夫人手在书页边；少年视线仍朝书卷",
            "翻页前的短停，诵读将继续",
        ),
        "study_story_turn": state(
            "study_story_turn",
            "苏宅书斋",
            "纸灰、木棕与一盏稳定烛光",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "程夫人仍在案后，孩子们没有换位",
            "“党锢祸起”后的连续诵读，声音落向更沉的段落",
        ),
        "study_grief_quote": state(
            "study_grief_quote",
            "苏宅书斋",
            "日间室内压低，烛光更可见",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "三名少年面向案后，苏辙开始握紧书卷",
            "范滂辞母引文完成，最后一个字后留短屏息",
        ),
        "study_answer_ready": state(
            "study_answer_ready",
            "苏宅书斋",
            "纸页灰白，烛光稳定",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "全体仍在原位，程夫人准备接上母亲的回答",
            "引文尾音消散，孩子们不说话",
        ),
        "study_mother_answer": state(
            "study_mother_answer",
            "苏宅书斋",
            "烛光映在程夫人和书页边缘",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "程夫人视线从书页移向孩子，孩子们保持原位",
            "母亲回答清楚落地，苏轼眼神开始被点亮",
        ),
        "study_moral_pressure": state(
            "study_moral_pressure",
            "苏宅书斋",
            "烛花微亮后重新稳定",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "苏轼身体前倾，苏辙握卷，巢儿抱书屏息",
            "“美名/长寿”完成，房间进入道德压力的静默",
        ),
        "study_lamp_pop": state(
            "study_lamp_pop",
            "苏宅书斋",
            "烛花轻爆后回到稳定暖光",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "四人原位，视线短暂落向烛火",
            "一声孤立烛花后留空，不带新对白",
        ),
        "study_question_start": state(
            "study_question_start",
            "苏宅书斋",
            "烛花后的安静侧光",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "苏轼由低头抬眼看向程夫人，其他人不换位",
            "苏轼吸气准备发问",
        ),
        "study_question_held": state(
            "study_question_held",
            "苏宅书斋",
            "烛光压住背景，人物脸部自然可见",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.open.blank", "oil_lamp.one.steady"],
            "苏轼面向母亲，苏辙与巢儿仍看向两人",
            "“母亲答应吗”后的呼吸停住",
        ),
        "study_mother_reply": state(
            "study_mother_reply",
            "苏宅书斋",
            "稳定低暖烛光",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.closed", "oil_lamp.one.steady"],
            "程夫人放下书卷看苏轼，三名少年正对她",
            "母亲回答前的长停顿",
        ),
        "study_truth_complete": state(
            "study_truth_complete",
            "苏宅书斋",
            "价值句后烛光稳定，背景静下来",
            ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            ["history_book.closed", "oil_lamp.one.steady"],
            "程夫人面向全体；三名少年面向她，站位未交换",
            "“不可以没有人讲真话”落完，古琴散音只作短促尾声",
        ),
        "well_establish": state(
            "well_establish",
            "苏宅后院井台",
            "数日后午后薄云与竹影",
            ["character.su_zhe.young", "character.su_shi.young"],
            ["suzhe_book.one.closed", "well_rope.one", "grass_stem.one"],
            "苏辙在井台右侧；苏轼从画面右侧向左绕行",
            "硬切后先建立竹叶、井绳和脚步声",
        ),
        "well_reciting": state(
            "well_reciting",
            "苏宅后院井台",
            "湿润青石上的自然日光",
            ["character.su_zhe.young", "character.su_shi.young"],
            ["suzhe_book.one.open.blank", "well_rope.one", "grass_stem.one"],
            "苏辙坐定面向书卷；苏轼绕到左前",
            "苏辙背书，脚步与竹叶保持轻声",
        ),
        "well_distracted": state(
            "well_distracted",
            "苏宅后院井台",
            "竹影移动，人物肤色自然",
            ["character.su_zhe.young", "character.su_shi.young"],
            ["suzhe_book.one.open.blank", "well_rope.one", "grass_stem.one", "ants.one"],
            "苏轼在井台下方蹲下，苏辙仍在右侧坐定",
            "蚂蚁细响、草茎摩擦，背书暂被打断",
        ),
        "well_answer_ready": state(
            "well_answer_ready",
            "苏宅后院井台",
            "午后漫射光",
            ["character.su_zhe.young", "character.su_shi.young"],
            ["suzhe_book.one.open.blank", "well_rope.one", "grass_stem.one", "ants.one"],
            "苏轼蹲在前景偏左，苏辙面向他但仍坐井台",
            "上一句背书刚停，兄弟准备说话",
        ),
        "well_rise": state(
            "well_rise",
            "苏宅后院井台",
            "阳光穿过竹影，动作清楚",
            ["character.su_zhe.young", "character.su_shi.young"],
            ["suzhe_book.one.open.blank", "well_rope.one", "grass_stem.one", "ants.one"],
            "苏辙抬眼；苏轼从蹲姿直起，仍在右→左运动轴上",
            "苏辙揭短后苏轼紧接着反驳",
        ),
        "well_departure_start": state(
            "well_departure_start",
            "苏宅后院井台",
            "自然午后光",
            ["character.su_zhe.young", "character.su_shi.young"],
            ["suzhe_book.one.open.blank", "well_rope.one", "grass_stem.one"],
            "苏轼转向画面右方；苏辙留在井台",
            "短促脚步开始，兄弟对白已结束",
        ),
        "well_departure_complete": state(
            "well_departure_complete",
            "苏宅后院井台",
            "竹影与青石稳定",
            ["character.su_zhe.young"],
            ["suzhe_book.one.open.blank", "well_rope.one"],
            "苏轼离开右边缘，苏辙望向哥哥离开方向",
            "脚步远去，苏辙吸气准备低声自语",
        ),
        "well_bright_one": state(
            "well_bright_one",
            "苏宅后院井台",
            "午后柔光收束在苏辙脸上",
            ["character.su_zhe.young"],
            ["suzhe_book.one.open.blank", "well_rope.one"],
            "苏辙望向右上方后将目光落回书卷",
            "“最亮的那一个”后留下温和笑意",
        ),
        "kitchen_establish": state(
            "kitchen_establish",
            "苏宅灶房",
            "冷青灰夜色与一盏暖油灯将入",
            ["character.chaoer.young"],
            ["stove.one", "ash.area.one", "oil_lamp.none_at_start"],
            "巢儿在灶台左后与灰边之间，右侧门半开",
            "最后一锅水落下，灶房低声与余热",
        ),
        "kitchen_writing": state(
            "kitchen_writing",
            "苏宅灶房",
            "冷暗空间，灰面获得一小片侧光",
            ["character.chaoer.young"],
            ["stove.one", "ash.area.one", "ash_strokes.two_simple", "oil_lamp.none_at_start"],
            "巢儿右手食指在灰面由左向右写，身体朝灶台",
            "手指摩擦柴灰，巢儿先看门再落指",
        ),
        "kitchen_lamp_enters": state(
            "kitchen_lamp_enters",
            "苏宅灶房",
            "一盏暖油灯从右侧门口照进冷灰",
            ["character.chaoer.young", "character.cheng_furen"],
            ["stove.one", "ash.area.one", "ash_strokes.two_simple", "oil_lamp.one"],
            "程夫人在右侧门口；巢儿跪在灰边",
            "灯玻璃轻响，巢儿惊吸气",
        ),
        "kitchen_wrist_held": state(
            "kitchen_wrist_held",
            "苏宅灶房",
            "油灯暖光固定在手腕与灰面",
            ["character.chaoer.young", "character.cheng_furen"],
            ["stove.one", "ash.area.one", "ash_strokes.two_simple", "oil_lamp.one"],
            "程夫人左手按住巢儿写字手腕，右手提灯；灰面未被抹掉",
            "“别抹。写的什么？”近距离清楚",
        ),
        "kitchen_answer": state(
            "kitchen_answer",
            "苏宅灶房",
            "冷灰与暖灯的局部对照",
            ["character.chaoer.young", "character.cheng_furen"],
            ["stove.one", "ash.area.one", "ash_strokes.two_simple", "oil_lamp.one"],
            "巢儿抬眼但手腕仍被固定，程夫人看灰再看人",
            "巢儿细声回答，灰字准确文字交给 POST-001",
        ),
        "kitchen_invitation": state(
            "kitchen_invitation",
            "苏宅灶房",
            "暖灯照出巢儿冻裂手背",
            ["character.chaoer.young", "character.cheng_furen"],
            ["stove.one", "ash.area.one", "ash_strokes.two_simple", "oil_lamp.one"],
            "程夫人看巢儿手背，巢儿从不敢相信到抬头",
            "邀请台词落地，箫声只作极轻的本段尾点",
        ),
        "kitchen_turn_start": state(
            "kitchen_turn_start",
            "苏宅灶房",
            "油灯仍在右手，门口有暖光出口",
            ["character.chaoer.young", "character.cheng_furen"],
            ["stove.one", "ash.area.one", "ash_strokes.two_simple", "oil_lamp.one"],
            "程夫人已开始向右侧半开门转身，巢儿仍跪灰边",
            "“让我听课？”后的半拍停顿",
        ),
        "kitchen_threshold": state(
            "kitchen_threshold",
            "苏宅灶房门口",
            "门槛冷暗与油灯暖光形成一条侧光",
            ["character.chaoer.young", "character.cheng_furen"],
            ["stove.one", "ash.area.one", "ash_strokes.two_simple", "oil_lamp.one"],
            "程夫人在门槛停下回头，巢儿在画面左后留在灰边",
            "脚步暂停，准备留下第一句格言",
        ),
        "kitchen_moral_line": state(
            "kitchen_moral_line",
            "苏宅灶房门口",
            "油灯照灰面与门框，灰字仍未消失",
            ["character.chaoer.young", "character.cheng_furen"],
            ["stove.one", "ash.area.one", "ash_strokes.two_simple", "oil_lamp.one"],
            "程夫人回头看巢儿后向门外移动，巢儿独留灰边",
            "“字如其人”后接“灰会散——你写下来的，不会”",
        ),
        "kitchen_exit": state(
            "kitchen_exit",
            "苏宅灶房",
            "油灯离开，冷暗重新占主导",
            ["character.chaoer.young"],
            ["stove.one", "ash.area.one", "ash_strokes.two_simple", "oil_lamp.outside"],
            "程夫人出半开门，巢儿低头看未被抹掉的灰字",
            "门外脚步远去，灶房只剩余烬与巢儿呼吸",
        ),
        "corridor_establish": state(
            "corridor_establish",
            "苏宅书斋外廊",
            "数日后日偏西暮金侧光",
            ["character.chaoer.young", "character.su_shi.young"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "巢儿靠左捧一卷书；苏轼靠右廊柱",
            "竹叶、远鸟和拘谨读书气息建立廊下",
        ),
        "corridor_reading": state(
            "corridor_reading",
            "苏宅书斋外廊",
            "暮金侧逆光与竹青阴影",
            ["character.chaoer.young", "character.su_shi.young"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "巢儿目光沿书页，苏轼面对他作小幅纠正",
            "巢儿读短句，声音仍拘谨但比灶房更稳",
        ),
        "corridor_praise": state(
            "corridor_praise",
            "苏宅书斋外廊",
            "日偏西光线稳定",
            ["character.chaoer.young", "character.su_shi.young"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "苏轼转向巢儿带鼓励笑意，巢儿仍持一卷书",
            "苏轼夸赞，空气转轻",
        ),
        "corridor_defensive_reply": state(
            "corridor_defensive_reply",
            "苏宅书斋外廊",
            "暮金侧光照到两人的肩线",
            ["character.chaoer.young", "character.su_shi.young"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "巢儿小幅摆手，苏轼仍在右侧，屏幕方向不变",
            "“借我十个胆子也不敢——”未完，右后脚步逼近",
        ),
        "corridor_servant_edge": state(
            "corridor_servant_edge",
            "苏宅书斋外廊",
            "暮金侧逆光，右后入口更亮",
            ["character.chaoer.young", "character.su_shi.young", "character.old_servant"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "老仆已在右后边缘，苏轼与巢儿共同转向他",
            "急促脚步和老仆喘气已经进入，尚未宣告",
        ),
        "corridor_announcement": state(
            "corridor_announcement",
            "苏宅书斋外廊",
            "右后入口的暖亮空气感增强",
            ["character.chaoer.young", "character.su_shi.young", "character.old_servant"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "老仆向左一步面向苏轼，巢儿留在左侧",
            "提亲宣告完整说完，不生成任何婚书文字",
        ),
        "corridor_red_ears": state(
            "corridor_red_ears",
            "苏宅书斋外廊",
            "暮金光照出苏轼耳根慢慢变红",
            ["character.chaoer.young", "character.su_shi.young", "character.old_servant"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "苏轼冻结在中右，巢儿观察他的脸，老仆守边",
            "宣告尾音后短停，巢儿准备追问",
        ),
        "corridor_question": state(
            "corridor_question",
            "苏宅书斋外廊",
            "自然暮金，不新增文字道具",
            ["character.chaoer.young", "character.su_shi.young", "character.old_servant"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "巢儿掰指追问；苏轼耳红不语；老仆仍在右后",
            "追问以拖尾破折号结束但视频不截断",
        ),
        "corridor_suzhe_appears": state(
            "corridor_suzhe_appears",
            "苏宅书斋外廊",
            "暮金侧光在柱后形成层次",
            ["character.chaoer.young", "character.su_shi.young", "character.old_servant", "character.su_zhe.young"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "苏辙从柱后站定，苏轼耳红，巢儿手指停住",
            "提亲宣告后的社会性静止，不新增对白",
        ),
        "corridor_tease": state(
            "corridor_tease",
            "苏宅书斋外廊",
            "暮金光线保持，气氛转为轻快",
            ["character.chaoer.young", "character.su_shi.young", "character.old_servant", "character.su_zhe.young"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "苏辙面对苏轼；苏轼作势追向右侧；巢儿让开",
            "调侃落地，轻快丝竹只在结尾段内进入",
        ),
        "corridor_chase": state(
            "corridor_chase",
            "苏宅书斋外廊",
            "明亮暮金扩大到院墙方向",
            ["character.chaoer.young", "character.su_shi.young", "character.su_zhe.young"],
            ["chaoer_book.one.blank", "corridor_pillar.one", "powder_wall.one"],
            "苏辙绕柱向右，苏轼从相反侧跟上，巢儿在中后方",
            "三人笑声与轻脚步，动作无碰撞无武打",
        ),
        "corridor_birds_rise": state(
            "corridor_birds_rise",
            "苏宅书斋外廊至院墙",
            "镜头升高，明亮天空与粉墙占比增加",
            ["character.chaoer.young", "character.su_shi.young", "character.su_zhe.young", "egrets.group"],
            ["chaoer_book.one.blank", "powder_wall.one", "egrets.group"],
            "三人仍在廊下可辨，白鹭从粉墙后向上飞起",
            "笑声、衣摆、竹叶与白鹭翅声完成收束",
        ),
    }


def build_document() -> dict[str, Any]:
    s = build_states()

    scenes = [
        {
            "id": "scene.study",
            "order": 1,
            "purpose": "让家庭课堂把范滂的选择变成三个少年共同承受的伦理压力",
            "turn": "程夫人的故事从史书落到苏轼主动发问与母亲定下价值判断",
            "next_obligation": "把价值句的余韵留在下一场轻快的兄弟关系中，不携带书斋错误道具",
            "location": "1056年眉山苏宅书斋，日间内景",
            "cast": ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"],
            "entry_state": s["study_open"],
            "exit_state": s["study_truth_complete"],
            "bridge_from_previous": None,
        },
        {
            "id": "scene.well",
            "order": 2,
            "purpose": "用井台的行走与背书展示苏轼的灵动、苏辙的克制和兄弟间的暗涌",
            "turn": "苏辙揭短后苏轼以走着写反驳，随后离开，苏辙留下复杂的赞叹",
            "next_obligation": "硬切到夜间灶房，让巢儿的学习线重新成为主线",
            "location": "1056年眉山苏宅后院井台，数日后日间外景",
            "cast": ["character.su_shi.young", "character.su_zhe.young"],
            "entry_state": s["well_establish"],
            "exit_state": s["well_bright_one"],
            "bridge_from_previous": {
                "type": "hard_scene_change",
                "description": "书斋价值句与古琴散音完成后，时间推进到数日后，井台重新建立人物与空间，不复用书斋烛火或站位。",
            },
        },
        {
            "id": "scene.kitchen",
            "order": 3,
            "purpose": "让巢儿从灰上的偷学动作进入被看见、被允许听课的关系转折",
            "turn": "程夫人先阻止抹灰，再看见冻裂的手并发出堂下听课邀请",
            "next_obligation": "灯离开而字留下，数日后必须在廊下兑现巢儿的学习进步",
            "location": "1056年眉山苏宅灶房，夜间内景",
            "cast": ["character.chaoer.young", "character.cheng_furen"],
            "entry_state": s["kitchen_establish"],
            "exit_state": s["kitchen_exit"],
            "bridge_from_previous": {
                "type": "hard_scene_change",
                "description": "井台兄弟对白结束后不做声音桥，直接切到夜灶房；灶膛余灰和巢儿的劳作状态重新建立。",
            },
        },
        {
            "id": "scene.corridor",
            "order": 4,
            "purpose": "兑现巢儿的学习进步，并以提亲消息把伦理压力释放成家庭喜剧钩子",
            "turn": "老仆带来提亲消息，苏轼耳红，苏辙用调侃引发三人追闹和白鹭收束",
            "next_obligation": "把王家小姐与婚事疑问留给下一章",
            "location": "1056年眉山苏宅书斋外廊与院墙，数日后日偏西外景",
            "cast": ["character.chaoer.young", "character.su_shi.young", "character.su_zhe.young", "character.old_servant"],
            "entry_state": s["corridor_establish"],
            "exit_state": s["corridor_birds_rise"],
            "bridge_from_previous": {
                "type": "hard_time_change",
                "description": "灶房门外的灯与灰停在上一场，时间推进数日，廊下以一卷借来的空白书兑现巢儿获准学习。",
            },
        },
    ]

    panels_spec = [
        ("P001", 1, "scene.study", 10.0, "study_open", "study_page_ready", "C001", "C003", "无", "课堂建立与开卷", "四人身份、书斋空间与开卷诵读完成建立"),
        ("P002", 2, "scene.study", 15.0, "study_page_ready", "study_answer_ready", "C004", "C006", "C003", "范滂辞母", "继续诵读，不回卷；引文结束后把回答交给下一Panel"),
        ("P003", 3, "scene.study", 13.0, "study_answer_ready", "study_lamp_pop", "C007", "C009", "C006", "母亲回答与烛花", "母亲回答落地，孩子反应压到烛花后的静默"),
        ("P004", 4, "scene.study", 14.0, "study_lamp_pop", "study_truth_complete", "C010", "C012", "C009", "母训定锚", "苏轼发问，程夫人回答并完成价值句"),
        ("P005", 5, "scene.well", 10.0, "well_establish", "well_answer_ready", "C013", "C015", "C012", "井台兄弟建立", "硬切后建立背书、走神、蚂蚁目标，停在对白前"),
        ("P006", 6, "scene.well", 11.0, "well_answer_ready", "well_bright_one", "C016", "C018", "C015", "揭短、反驳与暗涌", "按原文顺序完成揭短、走着写、离开和最亮的一个"),
        ("P007", 7, "scene.kitchen", 10.0, "kitchen_establish", "kitchen_wrist_held", "C019", "C021", "C018", "灰上写字与按腕", "建立巢儿写灰、程夫人入场并按住手腕"),
        ("P008", 8, "scene.kitchen", 11.0, "kitchen_wrist_held", "kitchen_turn_start", "C022", "C024", "C021", "回答与听课邀请", "保留手腕、灰面、油灯连续，程夫人开始转身"),
        ("P009", 9, "scene.kitchen", 10.0, "kitchen_turn_start", "kitchen_exit", "C025", "C027", "C024", "字留下", "走到门口回头说完两句，灯离开而灰字保留"),
        ("P010", 10, "scene.corridor", 8.0, "corridor_establish", "corridor_servant_edge", "C028", "C030", "C027", "廊下读书与脚步", "数日后兑现听课邀请，老仆只入边缘不宣告"),
        ("P011", 11, "scene.corridor", 13.0, "corridor_servant_edge", "corridor_suzhe_appears", "C031", "C033", "C030", "提亲消息与耳红", "宣告、追问、耳红、苏辙现身，暂不调侃"),
        ("P012", 12, "scene.corridor", 10.0, "corridor_suzhe_appears", "corridor_birds_rise", "C034", "C036", "C033", "调侃追闹与白鹭", "从苏辙已站定开始调侃，轻闹后拉高收束"),
    ]

    panels: list[dict[str, Any]] = []
    for panel_id, order, scene_id, duration_s, entry_id, exit_id, first_shot, last_shot, previous_shot, purpose, bridge in panels_spec:
        panels.append(
            {
                "id": panel_id,
                "order": order,
                "scene_id": scene_id,
                "duration_s": duration_s,
                "entry_state": s[entry_id],
                "exit_state": s[exit_id],
                "shot_ids": [f"C{number:03d}" for number in range((order - 1) * 3 + 1, order * 3 + 1)],
                "coverage_ids": [f"EV{number:03d}" for number in range((order - 1) * 3 + 1, order * 3 + 1)],
                "transition_to_next": None
                if order == 12
                else {
                    "ownership": "next",
                    "bridge": f"{bridge}；下一Panel从真实尾帧 {last_shot} 直接接续，不复演上一Panel的收尾动作。",
                },
            }
        )

    shot_specs = [
        ("C001", "P001", "scene.study", "study_open", "study_reciting_start", "建立四名角色、书斋与开卷关系", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], "character.identity_and_staging", "dolly_in_slow", ["D001"], "episodes/ep002.md:8-11", "must_show", "四人以稳定站位进入书斋，程夫人开卷诵读，巢儿在边缘听见声音"),
        ("C002", "P001", "scene.study", "study_reciting_start", "study_listening", "让三个少年被书声吸住并保持站位", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], "listener_gaze_settles", "fixed", [], "episodes/ep002.md:8-11", "optional", "苏轼、苏辙和巢儿都明确朝向书卷与程夫人，巢儿靠近但不跨入课堂中心"),
        ("C003", "P001", "scene.study", "study_listening", "study_page_ready", "以空白书页与烛火锁住下一Panel首帧", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], "page_and_lamp_hold", "tilt_down_slow", [], "episodes/ep002.md:8-12", "must_show", "史书摊开但不可读，烛火稳定，四人进入可继续诵读的静止态"),
        ("C004", "P002", "scene.study", "study_page_ready", "study_story_turn", "承接翻页后的范滂故事转折", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["tail.P001.real"], "continue_recitation", "dolly_in_slow", ["D002"], "episodes/ep002.md:12-16", "must_explain", "从上一Panel真实尾帧继续，程夫人直接说党锢祸起，不重演翻书"),
        ("C005", "P002", "scene.study", "study_story_turn", "study_grief_quote", "让范滂辞母引文完整通过声音与反应落地", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["tail.P001.real"], "deliver_grief_quote", "tilt_down_slow", ["D003", "D004"], "episodes/ep002.md:16-20", "must_explain", "母亲声音连续说完范滂辞母两句，页面保持空白，苏辙握卷"),
        ("C006", "P002", "scene.study", "study_grief_quote", "study_answer_ready", "把引文尾声交给下一Panel的母亲回答", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["tail.P001.real"], "hold_breath_after_quote", "cut_to_reaction", [], "episodes/ep002.md:20-22", "must_show", "引文结束后孩子屏息，程夫人准备回答而不提前说出下一句"),
        ("C007", "P003", "scene.study", "study_answer_ready", "study_mother_answer", "让母亲的回答明确归属于程夫人", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["tail.P002.real"], "mother_answers", "push_in_slow", ["D005"], "episodes/ep002.md:22-25", "must_explain", "程夫人直接接“他的母亲回答”，不回卷、不新增旁白"),
        ("C008", "P003", "scene.study", "study_mother_answer", "study_moral_pressure", "完成美名与长寿的两难并让苏轼眼神亮起", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["tail.P002.real"], "moral_pressure_lands", "cut_to_two_shot", ["D006"], "episodes/ep002.md:25-27", "must_explain", "第二句仍由程夫人说，苏轼反应增强但没有抢台词"),
        ("C009", "P003", "scene.study", "study_moral_pressure", "study_lamp_pop", "以烛花和静默把道德压力定格", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["tail.P002.real"], "lamp_pop_and_silence", "tilt_down_slow", [], "episodes/ep002.md:27-29", "must_show", "烛花孤响后四人仍在原位，给P004的苏轼抬头留出真实起点"),
        ("C010", "P004", "scene.study", "study_lamp_pop", "study_question_held", "让苏轼主动把历史问题问到自己身上", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["tail.P003.real"], "sushi_raises_and_asks", "push_in_slow", ["D007"], "episodes/ep002.md:29-33", "must_explain", "从烛花后静止直接由苏轼发问，不重演烛花"),
        ("C011", "P004", "scene.study", "study_question_held", "study_mother_reply", "把母亲的回答置于苏轼的等待中", ["character.cheng_furen", "character.su_shi.young"], ["tail.P003.real"], "mother_replies_after_pause", "fixed", ["D008"], "episodes/ep002.md:33-36", "must_explain", "程夫人放下书卷，停顿后回答，其他少年不抢镜"),
        ("C012", "P004", "scene.study", "study_mother_reply", "study_truth_complete", "用价值句完成书斋段落的定锚", ["character.cheng_furen", "character.su_shi.young", "character.su_zhe.young", "character.chaoer.young"], ["tail.P003.real"], "truth_line_and_resolve", "dolly_in_slow", ["D009"], "episodes/ep002.md:36-40", "must_show", "程夫人环视全体说完价值句，古琴散音不遮台词"),
        ("C013", "P005", "scene.well", "well_establish", "well_reciting", "硬切后建立井台与苏辙背书", ["character.su_zhe.young", "character.su_shi.young"], ["character.su_zhe.young", "character.su_shi.young"], "well_scene_establishes", "truck_left_slow", [], "episodes/ep002.md:44-48", "must_show", "井台、竹影、井绳和苏辙持一卷书建立，苏轼从右侧绕入"),
        ("C014", "P005", "scene.well", "well_reciting", "well_distracted", "完成兄弟提示与苏轼回答", ["character.su_zhe.young", "character.su_shi.young"], ["character.su_zhe.young", "character.su_shi.young"], "brothers_recite_exchange", "fixed", ["D010", "D011"], "episodes/ep002.md:48-53", "must_explain", "两句背书对白按顺序出现，书卷始终在苏辙手中"),
        ("C015", "P005", "scene.well", "well_distracted", "well_answer_ready", "将苏轼停在蚂蚁目标上作为真实跳起起点", ["character.su_zhe.young", "character.su_shi.young"], ["character.su_zhe.young", "character.su_shi.young"], "ants_hold_the_focus", "tilt_down_slow", [], "episodes/ep002.md:53-55", "must_show", "苏轼蹲看蚂蚁，苏辙坐定握卷，下一Panel不重新蹲下或绕行"),
        ("C016", "P006", "scene.well", "well_answer_ready", "well_rise", "按原文先揭短再让苏轼跳起反驳", ["character.su_zhe.young", "character.su_shi.young"], ["tail.P005.real"], "father_observation_then_sushi_rises", "tilt_up_slow", ["D012", "D013"], "episodes/ep002.md:55-59", "must_explain", "苏辙先说父亲评价，苏轼紧接着从蹲姿起身说走着写，两句各出现一次"),
        ("C017", "P006", "scene.well", "well_rise", "well_departure_complete", "让被说中的苏轼带笑离开而不复演对白", ["character.su_zhe.young", "character.su_shi.young"], ["tail.P005.real"], "sushi_walks_away", "track_right_slow", [], "episodes/ep002.md:59-61", "must_show", "苏轼带着被说中的笑意左向右离开，苏辙留在井台，不重复前两句"),
        ("C018", "P006", "scene.well", "well_departure_complete", "well_bright_one", "留下苏辙对哥哥的温和复杂感受", ["character.su_zhe.young"], ["tail.P005.real"], "suzhe_names_bright_one", "push_in_slow", ["D014"], "episodes/ep002.md:61-64", "must_explain", "苏辙低声说最亮的那一个，末态为淡笑与未松开的书卷"),
        ("C019", "P007", "scene.kitchen", "kitchen_establish", "kitchen_writing", "把巢儿的求知动作放在唯一灰面上", ["character.chaoer.young"], ["character.chaoer.young", "character.cheng_furen"], "write_two_strokes_in_ash", "dolly_in_slow", [], "episodes/ep002.md:68-72", "must_show", "巢儿确认无人后用一根手指在唯一灰面写两笔，POST-001负责“天地”确定文字"),
        ("C020", "P007", "scene.kitchen", "kitchen_writing", "kitchen_lamp_enters", "让程夫人和油灯从门口发现灰字", ["character.chaoer.young", "character.cheng_furen"], ["character.chaoer.young", "character.cheng_furen"], "lamp_enters_and_discovers", "pan_left_slow", [], "episodes/ep002.md:72-75", "must_show", "单盏油灯进入，程夫人站门口，巢儿惊动但尚未抹灰"),
        ("C021", "P007", "scene.kitchen", "kitchen_lamp_enters", "kitchen_wrist_held", "锁定按腕动作与提问", ["character.chaoer.young", "character.cheng_furen"], ["character.chaoer.young", "character.cheng_furen"], "mother_holds_wrist", "push_in_slow", ["D015"], "episodes/ep002.md:75-78", "must_explain", "程夫人左手按腕、右手提灯，灰面未被擦掉，台词属于程夫人"),
        ("C022", "P008", "scene.kitchen", "kitchen_wrist_held", "kitchen_answer", "让巢儿回答天地与先生的话", ["character.chaoer.young", "character.cheng_furen"], ["tail.P007.real"], "chaoer_answers", "tilt_up_slow", ["D016"], "episodes/ep002.md:78-82", "must_explain", "从真实按腕尾帧直接回答，巢儿仍为17岁男性劳作者"),
        ("C023", "P008", "scene.kitchen", "kitchen_answer", "kitchen_invitation", "把看见冻裂手转成堂下听课邀请", ["character.chaoer.young", "character.cheng_furen"], ["tail.P007.real"], "invitation_after_hand_observation", "cut_to_two_shot", ["D017", "D018"], "episodes/ep002.md:82-87", "must_explain", "程夫人先邀请，巢儿不敢相信地反问，油灯与手腕关系不跳变"),
        ("C024", "P008", "scene.kitchen", "kitchen_invitation", "kitchen_turn_start", "把邀请后的转身交给P009", ["character.chaoer.young", "character.cheng_furen"], ["tail.P007.real"], "mother_begins_to_turn", "track_right_slow", [], "episodes/ep002.md:87-89", "must_show", "程夫人开始向半开门转身，巢儿仍跪在灰边，油灯在右手"),
        ("C025", "P009", "scene.kitchen", "kitchen_turn_start", "kitchen_threshold", "完成程夫人走到门槛", ["character.chaoer.young", "character.cheng_furen"], ["tail.P008.real"], "mother_reaches_threshold", "track_right_slow", [], "episodes/ep002.md:89-92", "must_show", "从已开始转身的真实尾帧继续，不重演邀请或按腕"),
        ("C026", "P009", "scene.kitchen", "kitchen_threshold", "kitchen_moral_line", "留下字如其人的第一句", ["character.chaoer.young", "character.cheng_furen"], ["tail.P008.real"], "mother_turns_back_and_speaks", "push_in_slow", ["D019"], "episodes/ep002.md:92-95", "must_explain", "程夫人回头一次说字如其人，灰字和门方向不反转"),
        ("C027", "P009", "scene.kitchen", "kitchen_moral_line", "kitchen_exit", "完成灰会散与灯离开", ["character.chaoer.young", "character.cheng_furen"], ["tail.P008.real"], "mother_exits_leaving_ash", "pull_out_slow", ["D020"], "episodes/ep002.md:95-98", "must_show", "灰面保持未抹，程夫人带灯出门，POST-001锁定唯一可读天地"),
        ("C028", "P010", "scene.corridor", "corridor_establish", "corridor_reading", "数日后兑现巢儿获准听课", ["character.chaoer.young", "character.su_shi.young"], ["character.chaoer.young", "character.su_shi.young"], "chaoer_reads_one_book", "truck_right_slow", [], "episodes/ep002.md:103-106", "must_show", "巢儿成年男性捧一卷空白书读短句，苏轼在廊柱边听"),
        ("C029", "P010", "scene.corridor", "corridor_reading", "corridor_defensive_reply", "让学习进步变成轻微兄弟玩笑", ["character.chaoer.young", "character.su_shi.young"], ["character.chaoer.young", "character.su_shi.young"], "praise_and_defensive_reply", "fixed", ["D021", "D022"], "episodes/ep002.md:106-110", "must_explain", "苏轼夸赞与巢儿摆手原文出现，书卷只在巢儿手中"),
        ("C030", "P010", "scene.corridor", "corridor_defensive_reply", "corridor_servant_edge", "让提亲消息从脚步而不是字幕进入", ["character.chaoer.young", "character.su_shi.young", "character.old_servant"], ["character.chaoer.young", "character.su_shi.young"], "servant_approaches_edge", "pan_right_fast", [], "episodes/ep002.md:110-112", "must_show", "老仆从右后急促进入边缘，两位学习者共同转向，不提前说媒人内容"),
        ("C031", "P011", "scene.corridor", "corridor_servant_edge", "corridor_announcement", "完整交代提亲消息", ["character.chaoer.young", "character.su_shi.young", "character.old_servant"], ["tail.P010.real"], "servant_delivers_proposal_news", "dolly_in_slow", ["D023"], "episodes/ep002.md:112-116", "must_show", "从老仆已在边缘的真实尾帧直接完整宣告，不生成婚书文字"),
        ("C032", "P011", "scene.corridor", "corridor_announcement", "corridor_question", "以耳红与巢儿追问展开喜剧反应", ["character.chaoer.young", "character.su_shi.young", "character.old_servant"], ["tail.P010.real"], "red_ears_and_question", "push_in_slow", ["D024"], "episodes/ep002.md:116-119", "must_explain", "苏轼耳根慢慢红，巢儿掰指追问，老仆不新增解释"),
        ("C033", "P011", "scene.corridor", "corridor_question", "corridor_suzhe_appears", "让苏辙从柱后现身但暂不调侃", ["character.chaoer.young", "character.su_shi.young", "character.old_servant", "character.su_zhe.young"], ["tail.P010.real"], "suzhe_appears_and_settles", "pan_left_slow", [], "episodes/ep002.md:119-121", "must_show", "苏辙站定，苏轼耳红，巢儿手指停住，保持下一Panel调侃起点"),
        ("C034", "P012", "scene.corridor", "corridor_suzhe_appears", "corridor_tease", "以苏辙调侃直接释放前一Panel压力", ["character.chaoer.young", "character.su_shi.young", "character.su_zhe.young", "character.old_servant"], ["tail.P011.real"], "suzhe_teases", "track_left_slow", ["D025"], "episodes/ep002.md:121-124", "must_explain", "从苏辙已站定的真实尾帧直接说调侃，不重演现身"),
        ("C035", "P012", "scene.corridor", "corridor_tease", "corridor_chase", "以轻闹而非武打完成三人关系可读性", ["character.chaoer.young", "character.su_shi.young", "character.su_zhe.young"], ["tail.P011.real"], "playful_chase_without_contact", "truck_left_normal", [], "episodes/ep002.md:124-127", "optional", "苏轼作势追打、苏辙绕柱、巢儿让开，三人不跌倒不碰撞"),
        ("C036", "P012", "scene.corridor", "corridor_chase", "corridor_birds_rise", "用白鹭与笑声完成本章钩子收束", ["character.chaoer.young", "character.su_shi.young", "character.su_zhe.young"], ["tail.P011.real"], "egrets_rise_over_wall", "crane_up_slow", [], "episodes/ep002.md:127-130", "must_show", "三人仍在廊下可辨，笑声漫过粉墙，白鹭从墙后升起"),
    ]

    shots: list[dict[str, Any]] = []
    coverage: list[dict[str, Any]] = []
    for index, spec in enumerate(shot_specs, start=1):
        shot_id, panel_id, scene_id, before_id, after_id, purpose, chars, refs, action, camera_move, dialogue_ids, source_ref, priority, event = spec
        coverage_id = f"EV{index:03d}"
        shots.append(
            {
                "id": shot_id,
                "order": index,
                "scene_id": scene_id,
                "panel_id": panel_id,
                "coverage_ids": [coverage_id],
                "dialogue_ids": dialogue_ids,
                "critical_characters": chars,
                "reference_keys": refs,
                "actions": [action],
                "camera_moves": [camera_move],
                "purpose": purpose,
                "state_before": s[before_id],
                "state_after": s[after_id],
                "text_strategy": "post" if shot_id in {"C019", "C027"} else "none",
                "post_asset": "POST-001" if shot_id in {"C019", "C027"} else None,
            }
        )
        coverage.append(
            {
                "id": coverage_id,
                "order": index,
                "scene_id": scene_id,
                "panel_id": panel_id,
                "shot_id": shot_id,
                "priority": priority,
                "source_refs": [source_ref],
                "event": event,
                "visible_proof": f"状态 {after_id} 必须在画面或声音中可核验：{event}",
                "before_state": s[before_id],
                "after_state": s[after_id],
            }
        )

    dialogues = [
        ("D001", "S1", "范滂，字孟博。登车揽辔，慨然有澄清天下之志……", "EV001", "C001"),
        ("D002", "S1", "党锢祸起，诏书急捕范滂。滂辞别老母——他说：", "EV004", "C004"),
        ("D003", "S1", "滂归黄泉，存亡各得其所。", "EV005", "C005"),
        ("D004", "S1", "惟愿母亲割舍不忍之心，勿增悲戚。", "EV005", "C005"),
        ("D005", "S1", "他的母亲回答：你今日得以与李膺、杜密齐名，死了又有什么遗憾！", "EV007", "C007"),
        ("D006", "S1", "既想要美名，又想要长寿，天下哪有两全的事。", "EV008", "C008"),
        ("D007", "S2", "娘。孩儿若长大做了范滂，母亲答应吗？", "EV010", "C010"),
        ("D008", "S1", "你能做范滂，我就不能做范滂的母亲吗？", "EV011", "C011"),
        ("D009", "S1", "都记住——世上可以没有官。不可以没有人讲真话。", "EV012", "C012"),
        ("D010", "S3", "哥，《六国论》背到'较秦之所得'——下一句。", "EV014", "C014"),
        ("D011", "S2", "与战胜而得者，其实百倍。", "EV014", "C014"),
        ("D012", "S3", "爹说你文气纵横，就是坐不住。", "EV016", "C016"),
        ("D013", "S2", "坐着写出来的文章是死的。我得走着写。", "EV016", "C016"),
        ("D014", "S3", "……他永远是最亮的那一个。", "EV018", "C018"),
        ("D015", "S1", "别抹。写的什么？", "EV021", "C021"),
        ("D016", "S4", "天……地。先生说，饭管一天，字管一辈子。", "EV022", "C022"),
        ("D017", "S1", "明天起，活计做完了，搬个小凳坐到堂下去听。", "EV023", "C023"),
        ("D018", "S4", "夫人……让我听课？", "EV023", "C023"),
        ("D019", "S1", "字如其人。", "EV026", "C026"),
        ("D020", "S1", "灰会散——你写下来的，不会。", "EV027", "C027"),
        ("D021", "S2", "行啊。照这个进度，明年你就能给我挑错了。", "EV029", "C029"),
        ("D022", "S4", "借我十个胆子也不敢——", "EV029", "C029"),
        ("D023", "S5", "少爷！少爷！青神王方王贡士家遣了媒人，正候在堂上——说是为他家小姐提亲！", "EV031", "C031"),
        ("D024", "S4", "王小姐？哪个王小姐？就是听说琴棋书画样样——", "EV032", "C032"),
        ("D025", "S3", "书还没教完呢，先生这魂儿，先被人勾走了。", "EV034", "C034"),
    ]
    dialogue_records = [
        {"id": dialogue_id, "order": index, "speaker": speaker, "text": text, "coverage_id": coverage_id, "shot_id": shot_id}
        for index, (dialogue_id, speaker, text, coverage_id, shot_id) in enumerate(dialogues, start=1)
    ]

    return {
        "schema": "zero-to-story.creative-blueprint.v1",
        "project": {
            "title": "《一蓑烟雨》第二章·范滂传",
            "scope": "完整第二章短片：书斋范滂课、井台兄弟、灶房认字、廊下提亲钩子",
            "target_duration_s": 135.0,
        },
        "source": {
            "canonical": "episodes/ep002.md",
            "conflicts": [
                {
                    "id": "CONFLICT-001",
                    "question": "episode-directory.md 与 characters.md 将送第一支毛笔列为第二章事件，但 episodes/ep001.md 已完整呈现送笔。",
                    "resolution": "以完整剧本 episodes/ep001.md 与 episodes/ep002.md 的场次顺序为准；送笔属于第一章末尾，第二章不重复生成送笔，不把旧毛笔列为关键道具。",
                    "status": "resolved",
                },
                {
                    "id": "CONFLICT-002",
                    "question": "井台段的父亲评价、苏轼跳起台词和离开动作曾在Panel边界中出现错序或重复风险。",
                    "resolution": "以 episodes/ep002.md 的原文顺序为准：C016先由苏辙说“爹说你文气纵横，就是坐不住”，再由苏轼跳起说“坐着写出来的文章是死的。我得走着写”；C017只承接离开，C018说“最亮的那一个”。",
                    "status": "resolved",
                },
                {
                    "id": "CONFLICT-003",
                    "question": "部分旧提示词把17岁男性巢儿误写成maid/female，并可能让模型生成女性角色。",
                    "resolution": "本章所有巢儿引用统一绑定 character.chaoer.young，文本锁定为17岁近成年男性劳作者；视频提示词不再使用女性身份词。",
                    "status": "resolved",
                },
            ],
        },
        "scenes": scenes,
        "panels": panels,
        "coverage": coverage,
        "dialogue": dialogue_records,
        "generation": {
            "limits": {
                "reference_slots": 4,
                "max_critical_characters": 4,
                "max_actions": 1,
                "max_camera_moves": 1,
                "max_dialogue_lines": 2,
            },
            "policy": {
                "panel_equals_clip": True,
                "same_scene_boundary": "previous_panel_real_tail_is_exact_first_frame",
                "new_scene_boundary": "reference_generation_with_typed_identity_slots",
                "accepted_clip_tail": "extract_real_tail_png_with_ffmpeg_before_building_next_panel",
                "text_assets": {"POST-001": "天地", "POST-002": "dialogue_subtitles", "POST-003": "no_readable_background_text"},
            },
            "shots": shots,
        },
    }


def main() -> None:
    document = build_document()
    OUTPUT.write_text(json.dumps(document, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(OUTPUT)


if __name__ == "__main__":
    main()
