"""LFO Core — deterministic hashing, state machine, SQLite runtime, recovery."""
from .canonical import (
    LFO_CJ1_DUPLICATE_KEY,
    LFO_CJ1_ERROR,
    LFO_CJ1_FLOAT_FORBIDDEN,
    hash_bytes,
    hash_value,
    normalize_project_path,
    serialize,
    serialize_with_schema,
)
from .database import SCHEMA_VERSION, Database
from .hashing import (
    WORKFLOW_HASH_ALGORITHM,
    compute_compiler_identity,
    compute_content_hash,
    compute_dependency_hash,
    compute_file_hash,
    compute_idempotency_key,
    compute_params_hash,
    compute_workflow_hash,
)
from .invalidation import (
    get_active_invalidations,
    invalidate_upstream,
    resolve_invalidation,
)
from .recovery import (
    recover_project,
    recover_uncertain_journal,
)
from .runtime import (
    _log_event,
    create_asset,
    create_attempt,
    create_journal_entry,
    create_task,
    get_assets_by_task,
    get_attempt,
    get_attempts_by_task,
    get_events,
    get_journal,
    get_journal_by_attempt,
    get_project_state,
    get_task,
    get_tasks_by_project,
    promote_task_to_ready,
    transition_journal,
    update_task_hashes,
    update_task_status,
)
from .state_machine import (
    TASK_ACTIVE_STATES,
    TASK_BLOCKING_STATES,
    TASK_TERMINAL_STATES,
    FailureClassification,
    ProjectState,
    SubmissionState,
    Task,
    TaskStatus,
    compute_project_state,
    merge_run_status,
)
from .workflow_registry import (
    KNOWN_WORKFLOWS,
    BindingReport,
    FrameConstraints,
    InputSlot,
    ModelDependency,
    OutputSpec,
    ResolutionConstraints,
    ResourceProfile,
    WorkflowCapability,
    WorkflowManifest,
    WorkflowRegistry,
    make_capability,
)

__all__ = [
    # canonical
    "serialize",
    "serialize_with_schema",
    "hash_value",
    "hash_bytes",
    "normalize_project_path",
    # hashing
    "compute_content_hash",
    "compute_dependency_hash",
    "compute_params_hash",
    "compute_idempotency_key",
    "compute_compiler_identity",
    "compute_workflow_hash",
    "compute_file_hash",
    "WORKFLOW_HASH_ALGORITHM",
    # state machine
    "TaskStatus",
    "SubmissionState",
    "FailureClassification",
    "Task",
    "ProjectState",
    "compute_project_state",
    "merge_run_status",
    "TASK_TERMINAL_STATES",
    "TASK_ACTIVE_STATES",
    "TASK_BLOCKING_STATES",
    # database
    "Database",
    "SCHEMA_VERSION",
    # workflow registry
    "WorkflowManifest",
    "WorkflowCapability",
    "BindingReport",
    "WorkflowRegistry",
    "InputSlot",
    "ModelDependency",
    "FrameConstraints",
    "ResolutionConstraints",
    "ResourceProfile",
    "OutputSpec",
    "KNOWN_WORKFLOWS",
    "make_capability",
    # runtime
    "create_task",
    "get_task",
    "get_tasks_by_project",
    "update_task_status",
    "update_task_hashes",
    "promote_task_to_ready",
    "create_attempt",
    "get_attempt",
    "get_attempts_by_task",
    "create_journal_entry",
    "transition_journal",
    "get_journal",
    "get_journal_by_attempt",
    "create_asset",
    "get_assets_by_task",
    "get_project_state",
    "get_events",
    # recovery
    "recover_project",
    "recover_uncertain_journal",
    # invalidation
    "invalidate_upstream",
    "resolve_invalidation",
    "get_active_invalidations",
    # exceptions
    "LFO_CJ1_ERROR",
    "LFO_CJ1_FLOAT_FORBIDDEN",
    "LFO_CJ1_DUPLICATE_KEY",
]
